### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by yolandaas** [labsyspharm/minerva-author#43]
Occurs when trying to open minerva_author.exe and seems to be an issue with the version of Flask.

![image](https://user-images.githubusercontent.com/50094135/179043180-71bbdb00-3a40-4bf3-9e31-03ad194dca53.png)

**Comment by thejohnhoffer** [comment]
Hi! Thank you for raising this to my attention, it should be fixed in the latest 1.10.9 release! Please let me know if you continue to face issues running the executable.

-John

**Comment by yolandaas** [comment]
Hi John,

I downloaded and opened the newest version, and I am getting an "Invalid tiff file" error, saying that there are "not enough values to unpack (expected 2, got 1)". This specific tiff file has worked on previous versions of Minerva Author (i.e. pre-Jan 2022) so I wonder if it might be a problem with the requirements.

**Comment by thejohnhoffer** [comment]
Hi - would you be able to provide the full error log that you see when attempting to load your tiff file? I believe this error may be something that I have encountered before.

**Comment by Starahoush** [comment]
Hi John,

I am facing the same issue of "Invalid tiff file", "not enough values to unpack (expected 2, got 1)". I donwloaded the ome.tiff file from [nanostring ](https://nanostring.com/products/geomx-digital-spatial-profiler/spatial-organ-atlas/human-lymph-node/). I am not sure how to get the full error log but with you can guide me, I will reply as soon as possible. 

Here is the issue on the browser:
![browser](https://user-images.githubusercontent.com/67844695/193872992-51927ddc-4f12-4edb-a9fc-3cb4123528fc.JPG)

And here the message on the terminal:
![prompt](https://user-images.githubusercontent.com/67844695/193873026-8a792d9a-0f49-4c52-941a-c95f021e77e4.JPG)

I tried multiple times, that's why there are many occurences. I am currently using windows 10. Tried running on Chrome and Opera GX.

Thank you in advance,
Igor

**Comment by Starahoush** [comment]
Small update:

Not sure if this is helpful but the console says regarding the import tiff file issue:
value @ bundle.3652200fbef473bea6f2.js:280 

![browser_warning1](https://user-images.githubusercontent.com/67844695/193877599-01dd06d7-31f1-4f42-b5a9-b1840a59ae5a.JPG)
![browser_warning2](https://user-images.githubusercontent.com/67844695/193877240-711118a5-9144-45c1-807d-c4d245d3664c.JPG)

**Comment by thejohnhoffer** [comment]
@yolandaas @Starahoush -- The latest version of [Minerva Author v1.11.1](https://github.com/labsyspharm/minerva-author/releases/tag/v1.11.1) resolves this newer issue (#51) when tested on Windows 11. The source of the issue was outdated dependencies in the generated Windows executable for v1.10.
